### ISSUE TITLE
Report missing

### ISSUE THREAD

**Issue by tele-dev** [bartfish/AEII_2020_MSK_Bartlomiej#1]
Apart from the yml files, you also need a report showing their subsequent uses and effects (screenshots).

**Comment by bartfish** [comment]
@tele-dev the report is almost ready, we just need to add some missing conclusions/descriptions and upload it. It will be added today/tomorrow I think.

**Comment by bartfish** [comment]
@tele-dev the report is added here: https://github.com/bartfish/AEII_2020_MSK_Bartlomiej/blob/main/Project_Gitea/Gitea/Report_Project_Gitea_v1.pdf.
